# Generated by Django 5.2.8 on 2025-11-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_poster_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
